import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  TextInput,
  StyleSheet,
  Platform,
  Modal,
  Pressable,
  ActivityIndicator,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import AsyncStorage from '@react-native-async-storage/async-storage';

type ScheduleType = 'feeding' | 'sanitation';
type StatusType = 'active' | 'inactive';

// Pig Pen shape as loaded from api/schedules/get_farmer_pig_pens.php
type PigPen = {
  pen_id: number;
  pen_name: string;
  pig_count: number;
  pig_age_at_registration: number | string;
  avg_weight: number | string;
  currentAge: number | string;
  growthStage: string;
  feedType: string;
  recommendedFeed: string;
  source: string;
};


// NOTE: dapat naka-open at naka-RUN yung ngrok tunnel mo (ngrok http <port>)
// bago mo i-test 'to, kasi kailangan live yung URL na 'to para may sumagot.
const API_BASE_URL =
  'https://oinkmate.online/oinkmate-api';

// Validate manual time input such as "11:30 PM" or "7:05 am".
function isValidTime12Hour(time12h: string): boolean {
  return /^(0?[1-9]|1[0-2]):([0-5][0-9])\s*(AM|PM)$/i.test(time12h.trim());
}

// Convert "11:30 PM" -> "23:30:00" for the MySQL TIME column.
function convertTo24Hour(time12h: string): string {
  const match = time12h.trim().match(/^(0?[1-9]|1[0-2]):([0-5][0-9])\s*(AM|PM)$/i);
  if (!match) return '';

  let hours = parseInt(match[1], 10);
  const minutes = match[2];
  const modifier = match[3].toUpperCase();

  if (modifier === 'PM' && hours !== 12) hours += 12;
  if (modifier === 'AM' && hours === 12) hours = 0;

  return `${String(hours).padStart(2, '0')}:${minutes}:00`;
}

export default function AddScheduleScreen() {
  const router = useRouter();
  const [scheduleType, setScheduleType] = useState<ScheduleType>('feeding');

  // Pig Pen (feeding_schedules.pen_id / sanitation schedule pen_id)
  // Loaded from the database via api/schedules/get_farmer_pig_pens.php
  const [pigPens, setPigPens] = useState<PigPen[]>([]);
  const [loadingPens, setLoadingPens] = useState(false);
  const [selectedPen, setSelectedPen] = useState('');
  const [selectedPenId, setSelectedPenId] = useState<number | null>(null);
  const [showPenDropdown, setShowPenDropdown] = useState(false);

  // Feeding Time / Schedule Time (feeding_schedules.feeding_time / sanitation schedule time)
  const [selectedTime, setSelectedTime] = useState('');

  // Recommended Feed Amount (feeding_schedules.recommended_feed_amount)
  // NOTE: label in the UI is "Feed Amount Per Pig (kg)"; state/payload key kept
  // as-is on purpose so existing save logic is untouched.
  const [recommendedFeedAmount, setRecommendedFeedAmount] = useState('');

  // Pig Pen Information (pig_pen_records.pig_count / pig_age_at_registration)
  // Loaded from api/schedules/get_pen_information.php when a Pig Pen is selected.
  const [pigCount, setPigCount] = useState<number | null>(null);
  const [pigAgeAtRegistration, setPigAgeAtRegistration] = useState<number | string | null>(null);

  // Recommendation engine fields (generated by feeding_helper.php on the backend).
  // These are read-only, display-only values — nothing is calculated in React Native.
  const [currentAge, setCurrentAge] = useState<number | string | null>(null);
  const [growthStage, setGrowthStage] = useState<string | null>(null);
  const [feedType, setFeedType] = useState<string | null>(null);
  const [recommendedFeed, setRecommendedFeed] = useState<string | null>(null);
  const [source, setSource] = useState<string | null>(null);
  const [loadingPenInfo, setLoadingPenInfo] = useState(false);

  // Trigger Temperature (Optional; sanitation_schedules.trigger_temperature)
  const [triggerTemperature, setTriggerTemperature] = useState('');

  // Sanitation Duration (sanitation_schedules.duration_seconds — stored as total seconds)
  // Farmer enters Minutes + Seconds separately; combined into duration_seconds before saving.
  const [sanitationDurationMinutes, setSanitationDurationMinutes] = useState('15');
  const [sanitationDurationSeconds, setSanitationDurationSeconds] = useState('0');

  // Status (feeding_schedules.status / sanitation schedule status)
  const [status, setStatus] = useState<StatusType>('active');

  // Notes (optional)
  const [notes, setNotes] = useState('');

  // Save flow state
  const [showConfirmModal, setShowConfirmModal] = useState(false);
  const [saving, setSaving] = useState(false);
  const [showSuccessModal, setShowSuccessModal] = useState(false);
  const [showErrorModal, setShowErrorModal] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [errorTitle, setErrorTitle] = useState('Something Went Wrong');

  // Load the logged-in user's Pig Pens from the database.
  useEffect(() => {
    const loadPigPens = async () => {
      setLoadingPens(true);
      try {
        // The logged-in user session is stored in AsyncStorage on login.
        const storedUser = await AsyncStorage.getItem('user');
        if (!storedUser) {
          console.log('No logged-in user found in AsyncStorage');
          setLoadingPens(false);
          return;
        }

        const user = JSON.parse(storedUser);
        const farmer_id = user?.farmer_id ?? user?.id ?? user?.user_id;

        if (!farmer_id) {
          console.log('No farmer_id found on stored user session');
          setLoadingPens(false);
          return;
        }

        const response = await fetch(
          `${API_BASE_URL}/api/schedules/get_farmer_pig_pens.php?farmer_id=${farmer_id}`
        );
        const data = await response.json();

        if (data.success && Array.isArray(data.pig_pens)) {
          setPigPens(data.pig_pens);
          // Intentionally NOT auto-selecting the first pig pen here.
          // The user must explicitly choose a Pig Pen before any
          // pen-dependent info (Pig Pen Information / Feeding Computation)
          // is loaded or shown.
        } else {
          console.log('Failed to load pig pens:', data.message);
        }
      } catch (error) {
        console.log('Load pig pens error:', error);
      } finally {
        setLoadingPens(false);
      }
    };

    loadPigPens();
  }, []);

  // Load Pig Pen Information (pig_count, pig_age_at_registration) plus the
  // recommendation-engine fields (currentAge, growthStage, feedType,
  // recommendedFeed, source) whenever the selected pen changes.
  useEffect(() => {
    if (!selectedPenId) {
      setPigCount(null);
      setPigAgeAtRegistration(null);
      setCurrentAge(null);
      setGrowthStage(null);
      setFeedType(null);
      setRecommendedFeed(null);
      setSource(null);
      return;
    }

    const loadPenInformation = async () => {
      setLoadingPenInfo(true);
      try {
        const response = await fetch(
          `${API_BASE_URL}/api/schedules/get_pen_information.php?pen_id=${selectedPenId}`
        );
        const data = await response.json();

        if (data.success) {
          setPigCount(typeof data.pig_count === 'number' ? data.pig_count : parseInt(data.pig_count, 10));
          setPigAgeAtRegistration(data.pig_age_at_registration ?? null);
          setCurrentAge(data.currentAge ?? null);
          setGrowthStage(data.growthStage ?? null);
          setFeedType(data.feedType ?? null);
          setRecommendedFeed(data.recommendedFeed ?? null);
          setSource(data.source ?? null);
        } else {
          console.log('Failed to load pen information:', data.message);
          setPigCount(null);
          setPigAgeAtRegistration(null);
          setCurrentAge(null);
          setGrowthStage(null);
          setFeedType(null);
          setRecommendedFeed(null);
          setSource(null);
        }
      } catch (error) {
        console.log('Load pen information error:', error);
        setPigCount(null);
        setPigAgeAtRegistration(null);
        setCurrentAge(null);
        setGrowthStage(null);
        setFeedType(null);
        setRecommendedFeed(null);
        setSource(null);
      } finally {
        setLoadingPenInfo(false);
      }
    };

    loadPenInformation();
  }, [selectedPenId]);

  // Feeding Computation — Total Feed Required = Number of Pigs x Feed Amount Per Pig
  // Feed Per Container = Total Feed Required / 3
  const feedAmountPerPigValue = parseFloat(recommendedFeedAmount);
  const hasValidFeedComputation =
    scheduleType === 'feeding' &&
    typeof pigCount === 'number' &&
    !isNaN(pigCount) &&
    !isNaN(feedAmountPerPigValue);
  const totalFeedRequired = hasValidFeedComputation ? pigCount * feedAmountPerPigValue : null;
  const feedPerContainer = hasValidFeedComputation && totalFeedRequired !== null ? totalFeedRequired / 3 : null;

  const handleBack = () => {
    router.replace('/(tabs)/schedule');
  };

  const validate = (): string | null => {
    if (!selectedPen) return 'Please select a pig pen';
    if (!selectedTime.trim()) return 'Please enter a time';
    if (!isValidTime12Hour(selectedTime)) return 'Please enter the time in the format h:mm AM/PM (e.g. 11:30 PM)';

    if (scheduleType === 'feeding') {
      if (!recommendedFeedAmount.trim()) {
        return 'Please enter the recommended feed amount';
      }
      if (isNaN(parseFloat(recommendedFeedAmount))) {
        return 'Recommended feed amount must be a number';
      }
    }

    if (scheduleType === 'sanitation') {
      if (triggerTemperature.trim() && isNaN(parseFloat(triggerTemperature))) {
        return 'Trigger temperature must be a number';
      }

      if (!sanitationDurationMinutes.trim() || !sanitationDurationSeconds.trim()) {
        return 'Please enter the sanitation duration';
      }
      const minutesValue = Number(sanitationDurationMinutes);
      const secondsValue = Number(sanitationDurationSeconds);
      if (
        isNaN(minutesValue) ||
        !Number.isInteger(minutesValue) ||
        minutesValue < 0
      ) {
        return 'Sanitation duration minutes must be a whole number, 0 or greater';
      }
      if (
        isNaN(secondsValue) ||
        !Number.isInteger(secondsValue) ||
        secondsValue < 0 ||
        secondsValue > 59
      ) {
        return 'Sanitation duration seconds must be a whole number between 0 and 59';
      }
      if (minutesValue * 60 + secondsValue <= 0) {
        return 'Sanitation duration must be greater than 0 seconds';
      }
    }

    return null;
  };

  const handleSavePress = () => {
    const validationError = validate();
    if (validationError) {
      setErrorTitle('Something Went Wrong');
      setErrorMessage(validationError);
      setShowErrorModal(true);
      return;
    }
    setShowConfirmModal(true);
  };

  const handleConfirmSave = async () => {
    setShowConfirmModal(false);
    setSaving(true);

    try {
      const pen_id = selectedPenId;
      const endpoint =
        scheduleType === 'feeding'
          ? '/api/schedules/add_feeding_schedule.php'
          : '/api/schedules/add_sanitation_schedule.php';

      const payload =
        scheduleType === 'feeding'
          ? {
              pen_id,
              feeding_time: convertTo24Hour(selectedTime),
              feed_amount_per_pig: feedAmountPerPigValue,
              total_feed_required: totalFeedRequired,
              feed_per_container: feedPerContainer,
              status,
            }
          : {
              pen_id,
              schedule_time: convertTo24Hour(selectedTime),
              duration_seconds: Number(sanitationDurationMinutes) * 60 + Number(sanitationDurationSeconds),
              trigger_temperature: triggerTemperature.trim()
                ? parseFloat(triggerTemperature)
                : null,
              status,
            };

      const response = await fetch(`${API_BASE_URL}${endpoint}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      const data = await response.json();
      console.log(`${endpoint} response:`, data);

      if (data.success) {
        if (scheduleType === 'feeding') {
          // Reset Feeding-specific form field after a successful save.
          setRecommendedFeedAmount('');
        }
        if (scheduleType === 'sanitation') {
          // Reset Sanitation-specific form fields after a successful save.
          setSanitationDurationMinutes('15');
          setSanitationDurationSeconds('0');
        }
        setShowSuccessModal(true);
      } else {
        setErrorTitle(data.duplicate ? 'Duplicate Schedule' : 'Something Went Wrong');
        setErrorMessage(data.message || 'Failed to save schedule');
        setShowErrorModal(true);
      }
    } catch (error) {
      console.log('Save schedule error:', error);
      setErrorTitle('Something Went Wrong');
      setErrorMessage('Failed to save schedule. Please check your connection.');
      setShowErrorModal(true);
    } finally {
      setSaving(false);
    }
  };

  return (
    <View style={styles.screen}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity style={styles.backButton} onPress={handleBack} activeOpacity={0.8}>
          <Ionicons name="chevron-back" size={20} color="#2F5D50" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Add Schedule</Text>
        <View style={styles.headerPlaceholder} />
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
        keyboardShouldPersistTaps="handled"
      >
        {/* Schedule Type */}
        <View style={styles.card}>
          <View style={styles.cardLabelRow}>
            <Ionicons name="layers-outline" size={15} color="#2F5D50" />
            <Text style={styles.cardLabel}>Schedule Type</Text>
          </View>
          <View style={styles.segmentedControl}>
            <TouchableOpacity
              style={[styles.segment, scheduleType === 'feeding' && styles.segmentActive]}
              onPress={() => setScheduleType('feeding')}
              activeOpacity={0.85}
            >
              <Ionicons
                name="restaurant-outline"
                size={15}
                color={scheduleType === 'feeding' ? '#FFFFFF' : '#6B8A82'}
              />
              <Text style={[styles.segmentText, scheduleType === 'feeding' && styles.segmentTextActive]}>
                Feeding
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.segment, scheduleType === 'sanitation' && styles.segmentActive]}
              onPress={() => setScheduleType('sanitation')}
              activeOpacity={0.85}
            >
              <Ionicons
                name="water-outline"
                size={15}
                color={scheduleType === 'sanitation' ? '#FFFFFF' : '#6B8A82'}
              />
              <Text style={[styles.segmentText, scheduleType === 'sanitation' && styles.segmentTextActive]}>
                Sanitation
              </Text>
            </TouchableOpacity>
          </View>
        </View>

        {/* Pig Pen */}
        <View style={styles.card}>
          <View style={styles.cardLabelRow}>
            <Ionicons name="paw-outline" size={15} color="#2F5D50" />
            <Text style={styles.cardLabel}>Pig Pen</Text>
          </View>
          <View style={styles.dropdownWrapper}>
            <TouchableOpacity
              style={styles.dropdownTrigger}
              onPress={() => setShowPenDropdown(!showPenDropdown)}
              activeOpacity={0.85}
              disabled={loadingPens}
            >
              <Ionicons name="paw-outline" size={15} color="#2F5D50" />
              {loadingPens ? (
                <ActivityIndicator size="small" color="#2F5D50" />
              ) : (
                <Text style={styles.dropdownTriggerText}>
                  {selectedPen || (pigPens.length === 0 ? 'No pig pens found' : 'Select Pig Pen')}
                </Text>
              )}
              <Ionicons
                name={showPenDropdown ? 'chevron-up' : 'chevron-down'}
                size={15}
                color="#8A9994"
              />
            </TouchableOpacity>
            {showPenDropdown && (
              <View style={styles.dropdownMenu}>
                {pigPens.map((pen) => (
                  <TouchableOpacity
                    key={pen.pen_id}
                    style={[styles.dropdownItem, selectedPenId === pen.pen_id && styles.dropdownItemActive]}
                    onPress={() => {
                      setSelectedPen(pen.pen_name);
                      setSelectedPenId(pen.pen_id);
                      setShowPenDropdown(false);
                    }}
                    activeOpacity={0.8}
                  >
                    <Text style={[styles.dropdownItemText, selectedPenId === pen.pen_id && styles.dropdownItemTextActive]}>
                      {pen.pen_name}
                    </Text>
                    {selectedPenId === pen.pen_id && (
                      <Ionicons name="checkmark" size={14} color="#2F5D50" />
                    )}
                  </TouchableOpacity>
                ))}
              </View>
            )}
          </View>
        </View>

        {/* Pig Pen Information — shown once a pen is selected */}
        {selectedPenId && (
          <View style={styles.card}>
            <View style={styles.cardLabelRow}>
              <Ionicons name="information-circle-outline" size={15} color="#2F5D50" />
              <Text style={styles.cardLabel}>Pig Pen Information</Text>
            </View>
            {loadingPenInfo ? (
              <ActivityIndicator size="small" color="#2F5D50" />
            ) : (
              <View style={styles.infoList}>
                <View style={styles.infoRow}>
                  <Text style={styles.infoRowLabel}>Pig Age at Registration</Text>
                  <Text style={styles.infoRowValue}>{pigAgeAtRegistration ?? '—'}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoRowLabel}>Current Age</Text>
                  <Text style={styles.infoRowValue}>{currentAge ?? '—'}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoRowLabel}>Growth Stage</Text>
                  <Text style={styles.infoRowValue}>{growthStage ?? '—'}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoRowLabel}>Number of Pigs</Text>
                  <Text style={styles.infoRowValue}>
                    {typeof pigCount === 'number' && !isNaN(pigCount) ? pigCount : '—'}
                  </Text>
                </View>
              </View>
            )}
          </View>
        )}

        {/* Feeding Recommendation — generated by feeding_helper.php on the backend.
            Display-only; nothing here is calculated in React Native. */}
        {scheduleType === 'feeding' && selectedPenId && (
          <View style={styles.card}>
            <View style={styles.cardLabelRow}>
              <Ionicons name="nutrition-outline" size={15} color="#2F5D50" />
              <Text style={styles.cardLabel}>Feeding Recommendation</Text>
            </View>
            {loadingPenInfo ? (
              <ActivityIndicator size="small" color="#2F5D50" />
            ) : (
              <View style={styles.infoList}>
                <View style={styles.infoRow}>
                  <Text style={styles.infoRowLabel}>Feed Type</Text>
                  <Text style={styles.infoRowValue}>{feedType ?? '—'}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoRowLabel}>Recommended Feed Amount</Text>
                  <Text style={styles.infoRowValue}>{recommendedFeed ?? '—'}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoRowLabel}>Source</Text>
                  <Text style={styles.infoRowValue}>{source ?? '—'}</Text>
                </View>
              </View>
            )}
          </View>
        )}
        <View style={styles.card}>
          <View style={styles.cardLabelRow}>
            <Ionicons name="time-outline" size={15} color="#2F5D50" />
            <Text style={styles.cardLabel}>
              {scheduleType === 'feeding' ? 'Feeding Time' : 'Schedule Time'}
            </Text>
          </View>
          <View style={styles.timeInputWrapper}>
            <Ionicons name="alarm-outline" size={15} color="#2F5D50" />
            <TextInput
              style={styles.timeInput}
              placeholder="e.g. 11:00 PM"
              placeholderTextColor="#B0C0BC"
              value={selectedTime}
              onChangeText={setSelectedTime}
              autoCapitalize="characters"
              autoCorrect={false}
              keyboardType="default"
              maxLength={8}
            />
          </View>
          <Text style={styles.optionalLabel}>
            Use the format h:mm AM/PM (e.g. 11:30 PM).
          </Text>
        </View>

        {/* Feeding-only: Feed Amount Per Pig */}
        {scheduleType === 'feeding' && (
          <View style={styles.card}>
            <View style={styles.cardLabelRow}>
              <Ionicons name="nutrition-outline" size={15} color="#2F5D50" />
              <Text style={styles.cardLabel}>Feed Amount Per Pig (kg)</Text>
            </View>
            <TextInput
              style={styles.textField}
              placeholder="e.g. 2.5"
              placeholderTextColor="#B0C0BC"
              keyboardType="decimal-pad"
              value={recommendedFeedAmount}
              onChangeText={setRecommendedFeedAmount}
            />
          </View>
        )}

        {/* Feeding-only: Feeding Computation (Total Feed Required / Feed Per Container) */}
        {scheduleType === 'feeding' && hasValidFeedComputation && (
          <View style={styles.card}>
            <View style={styles.cardLabelRow}>
              <Ionicons name="calculator-outline" size={15} color="#2F5D50" />
              <Text style={styles.cardLabel}>Feeding Computation</Text>
            </View>
            <View style={styles.infoList}>
              <View style={styles.infoRow}>
                <Text style={styles.infoRowLabel}>Total Feed Required</Text>
                <Text style={styles.infoRowValue}>{totalFeedRequired?.toFixed(2)} kg</Text>
              </View>
              <View style={styles.infoRow}>
                <Text style={styles.infoRowLabel}>Feed Per Container</Text>
                <Text style={styles.infoRowValue}>{feedPerContainer?.toFixed(2)} kg</Text>
              </View>
            </View>
          </View>
        )}

        {/* Sanitation-only: Trigger Temperature (Optional) */}
        {scheduleType === 'sanitation' && (
          <View style={styles.card}>
            <View style={styles.cardLabelRow}>
              <Ionicons name="thermometer-outline" size={15} color="#2F5D50" />
              <Text style={styles.cardLabel}>Trigger Temperature <Text style={styles.optionalLabel}>(Optional)</Text></Text>
            </View>
            <TextInput
              style={styles.textField}
              placeholder="e.g. 32"
              placeholderTextColor="#B0C0BC"
              keyboardType="decimal-pad"
              value={triggerTemperature}
              onChangeText={setTriggerTemperature}
            />
            <Text style={styles.optionalLabel}>
              Leave blank if this schedule should always run at the scheduled time.
            </Text>
          </View>
        )}

        {/* Sanitation-only: Sanitation Duration (Minutes + Seconds) */}
        {scheduleType === 'sanitation' && (
          <View style={styles.card}>
            <View style={styles.cardLabelRow}>
              <Ionicons name="timer-outline" size={15} color="#2F5D50" />
              <Text style={styles.cardLabel}>Sanitation Duration</Text>
            </View>
            <View style={styles.durationRow}>
              <View style={styles.durationField}>
                <Text style={styles.durationFieldLabel}>Minutes</Text>
                <TextInput
                  style={styles.textField}
                  placeholder="e.g. 2"
                  placeholderTextColor="#B0C0BC"
                  keyboardType="number-pad"
                  value={sanitationDurationMinutes}
                  onChangeText={(text) => setSanitationDurationMinutes(text.replace(/[^0-9]/g, ''))}
                />
              </View>
              <View style={styles.durationField}>
                <Text style={styles.durationFieldLabel}>Seconds</Text>
                <TextInput
                  style={styles.textField}
                  placeholder="e.g. 30"
                  placeholderTextColor="#B0C0BC"
                  keyboardType="number-pad"
                  value={sanitationDurationSeconds}
                  onChangeText={(text) => setSanitationDurationSeconds(text.replace(/[^0-9]/g, ''))}
                />
              </View>
            </View>
            <Text style={styles.optionalLabel}>
              Whole numbers only. Seconds must be between 0 and 59. Total duration must be greater than 0.
            </Text>
          </View>
        )}

        {/* Status */}
        <View style={styles.card}>
          <View style={styles.cardLabelRow}>
            <Ionicons name="radio-button-on-outline" size={15} color="#2F5D50" />
            <Text style={styles.cardLabel}>Status</Text>
          </View>
          <View style={styles.segmentedControl}>
            <TouchableOpacity
              style={[styles.segment, status === 'active' && styles.segmentActive]}
              onPress={() => setStatus('active')}
              activeOpacity={0.85}
            >
              <Ionicons
                name="checkmark-circle-outline"
                size={15}
                color={status === 'active' ? '#FFFFFF' : '#6B8A82'}
              />
              <Text style={[styles.segmentText, status === 'active' && styles.segmentTextActive]}>
                Active
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.segment, status === 'inactive' && styles.segmentInactive]}
              onPress={() => setStatus('inactive')}
              activeOpacity={0.85}
            >
              <Ionicons
                name="pause-circle-outline"
                size={15}
                color={status === 'inactive' ? '#FFFFFF' : '#6B8A82'}
              />
              <Text style={[styles.segmentText, status === 'inactive' && styles.segmentTextInactive]}>
                Inactive
              </Text>
            </TouchableOpacity>
          </View>
        </View>

        {/* Notes */}
        <View style={styles.card}>
          <View style={styles.cardLabelRow}>
            <Ionicons name="document-text-outline" size={15} color="#2F5D50" />
            <Text style={styles.cardLabel}>Notes <Text style={styles.optionalLabel}>(Optional)</Text></Text>
          </View>
          <TextInput
            style={styles.notesInput}
            placeholder="Optional remarks..."
            placeholderTextColor="#B0C0BC"
            multiline
            numberOfLines={3}
            value={notes}
            onChangeText={setNotes}
            textAlignVertical="top"
          />
        </View>

        {/* Save Button */}
        <TouchableOpacity
          style={[styles.primaryButton, saving && styles.primaryButtonDisabled]}
          activeOpacity={0.85}
          onPress={handleSavePress}
          disabled={saving}
        >
          {saving ? (
            <>
              <ActivityIndicator size="small" color="#FFFFFF" />
              <Text style={styles.primaryButtonText}>Saving...</Text>
            </>
          ) : (
            <>
              <Ionicons name="checkmark-circle-outline" size={18} color="#FFFFFF" />
              <Text style={styles.primaryButtonText}>Save Schedule</Text>
            </>
          )}
        </TouchableOpacity>

        <View style={styles.bottomSpacer} />
      </ScrollView>

      {/* Save Confirmation Modal */}
      <Modal
        visible={showConfirmModal}
        transparent
        animationType="fade"
        statusBarTranslucent
      >
        <Pressable
          style={modalStyles.overlay}
          onPress={saving ? undefined : () => setShowConfirmModal(false)}
        >
          <Pressable style={modalStyles.modal} onPress={() => {}}>
            <View style={modalStyles.iconWrap}>
              <Ionicons name="checkmark-circle-outline" size={28} color="#2F5D50" />
            </View>

            <View style={modalStyles.textBlock}>
              <Text style={modalStyles.title}>Save Schedule?</Text>
              <Text style={modalStyles.subtitle}>
                Are you sure you want to save this{' '}
                {scheduleType === 'feeding' ? 'feeding' : 'sanitation'} schedule?
              </Text>
            </View>

            <View style={modalStyles.actions}>
              <TouchableOpacity
                style={modalStyles.cancelButton}
                onPress={() => setShowConfirmModal(false)}
              >
                <Text style={modalStyles.cancelButtonText}>Cancel</Text>
              </TouchableOpacity>

              <TouchableOpacity
                style={modalStyles.confirmButton}
                onPress={handleConfirmSave}
              >
                <Ionicons name="checkmark-circle-outline" size={15} color="#FFFFFF" />
                <Text style={modalStyles.confirmButtonText}>Save</Text>
              </TouchableOpacity>
            </View>
          </Pressable>
        </Pressable>
      </Modal>

      {/* Success Modal */}
      <Modal
        visible={showSuccessModal}
        transparent
        animationType="fade"
        statusBarTranslucent
      >
        <Pressable
          style={modalStyles.overlay}
          onPress={() => {
            setShowSuccessModal(false);
            router.replace('/(tabs)/schedule');
          }}
        >
          <Pressable style={modalStyles.modal} onPress={() => {}}>
            <View style={modalStyles.iconWrap}>
              <Ionicons name="checkmark-circle-outline" size={28} color="#2F5D50" />
            </View>

            <View style={modalStyles.textBlock}>
              <Text style={modalStyles.title}>Schedule Saved Successfully</Text>
              <Text style={modalStyles.subtitle}>
                The {scheduleType === 'feeding' ? 'feeding' : 'sanitation'} schedule has
                been added.
              </Text>
            </View>

            <View style={modalStyles.actions}>
              <TouchableOpacity
                style={modalStyles.confirmButton}
                onPress={() => {
                  setShowSuccessModal(false);
                  router.replace('/(tabs)/schedule');
                }}
              >
                <Text style={modalStyles.confirmButtonText}>OK</Text>
              </TouchableOpacity>
            </View>
          </Pressable>
        </Pressable>
      </Modal>

      {/* Error Modal */}
      <Modal
        visible={showErrorModal}
        transparent
        animationType="fade"
        statusBarTranslucent
      >
        <Pressable style={modalStyles.overlay} onPress={() => setShowErrorModal(false)}>
          <Pressable style={modalStyles.modal} onPress={() => {}}>
            <View style={[modalStyles.iconWrap, modalStyles.iconWrapError]}>
              <Ionicons name="alert-circle-outline" size={28} color="#C62828" />
            </View>

            <View style={modalStyles.textBlock}>
              <Text style={modalStyles.title}>{errorTitle}</Text>
              <Text style={modalStyles.subtitle}>{errorMessage}</Text>
            </View>

            <View style={modalStyles.actions}>
              <TouchableOpacity
                style={modalStyles.confirmButton}
                onPress={() => setShowErrorModal(false)}
              >
                <Text style={modalStyles.confirmButtonText}>OK</Text>
              </TouchableOpacity>
            </View>
          </Pressable>
        </Pressable>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F7F8F9',
  },

  /* Header */
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 48,
    paddingBottom: 14,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#EEF1F0',
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#EAF7F1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: '800',
    color: '#1A2D27',
    fontFamily: 'Arial',
    letterSpacing: -0.2,
  },
  headerPlaceholder: {
    width: 38,
  },

  /* Scroll */
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    gap: 12,
  },

  /* Card */
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: '#EEF1F0',
    shadowColor: '#0F2D24',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
  cardLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  cardLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A2D27',
    fontFamily: 'Arial',
  },
  optionalLabel: {
    fontFamily: 'Arial',
    fontSize: 15,
    fontWeight: '500',
    color: '#8A9994',
  },

  /* Segmented Control */
  segmentedControl: {
    flexDirection: 'row',
    backgroundColor: '#F0F3F2',
    borderRadius: 14,
    padding: 3,
    gap: 3,
  },
  segment: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 11,
  },
  segmentActive: {
    backgroundColor: '#2F5D50',
    shadowColor: '#0F2D24',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  segmentInactive: {
    backgroundColor: '#D96C8D',
    shadowColor: '#D96C8D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  segmentText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#6B8A82',
    fontFamily: 'Arial',
  },
  segmentTextActive: {
    color: '#FFFFFF',
  },
  segmentTextInactive: {
    color: '#FFFFFF',
  },

  /* Dropdown */
  dropdownWrapper: {
    gap: 8,
  },
  dropdownTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#F7F8F9',
    borderRadius: 14,
    paddingVertical: 13,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E2EDEA',
  },
  dropdownTriggerText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#1A2D27',
    fontFamily: 'Arial',
  },
  dropdownMenu: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2EDEA',
    overflow: 'hidden',
    shadowColor: '#0F2D24',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F3F2',
  },
  dropdownItemActive: {
    backgroundColor: '#EAF7F1',
  },
  dropdownItemText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A5C57',
    fontFamily: 'Arial',
  },
  dropdownItemTextActive: {
    color: '#2F5D50',
    fontWeight: '700',
  },

  /* Manual time input */
  timeInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#F7F8F9',
    borderRadius: 14,
    paddingVertical: 3,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E2EDEA',
  },
  timeInput: {
    flex: 1,
    paddingVertical: 10,
    fontSize: 16,
    fontWeight: '600',
    color: '#1A2D27',
    fontFamily: 'Arial',
  },

  /* Sanitation Duration (Minutes / Seconds) row */
  durationRow: {
    flexDirection: 'row',
    gap: 10,
  },
  durationField: {
    flex: 1,
    gap: 6,
  },
  durationFieldLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#4A5C57',
    fontFamily: 'Arial',
  },

  /* Single-line text field (Recommended Feed Amount, Trigger Temperature) */
  textField: {
    backgroundColor: '#F7F8F9',
    borderRadius: 14,
    paddingVertical: 13,
    paddingHorizontal: 14,
    fontSize: 16,
    color: '#1A2D27',
    fontFamily: 'Arial',
    borderWidth: 1,
    borderColor: '#E2EDEA',
  },

  /* Info rows (Pig Pen Information / Feeding Computation cards) */
  infoList: {
    gap: 8,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F7F8F9',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E2EDEA',
  },
  infoRowLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A5C57',
    fontFamily: 'Arial',
  },
  infoRowValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2F5D50',
    fontFamily: 'Arial',
  },

  /* Notes */
  notesInput: {
    backgroundColor: '#F7F8F9',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 16,
    color: '#1A2D27',
    fontFamily: 'Arial',
    borderWidth: 1,
    borderColor: '#E2EDEA',
    minHeight: 80,
  },

  /* Primary Button */
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#2F5D50',
    borderRadius: 20,
    paddingVertical: 16,
    marginTop: 4,
    shadowColor: '#0F2D24',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 4,
  },
  primaryButtonText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: 'Arial',
  },
  primaryButtonDisabled: {
    opacity: 0.7,
  },

  bottomSpacer: {
    height: 32,
  },
});

/* Modals — design kopya ng DeletePigPenModal (icon circle, title, subtitle, cancel/confirm row) */
const modalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(15,45,36,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  modal: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 24,
    alignItems: 'center',
    gap: 20,
  },
  iconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#EAF7F1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconWrapError: {
    backgroundColor: '#FCF0F3',
  },
  textBlock: {
    alignItems: 'center',
    gap: 8,
  },
  title: {
    fontFamily: 'Arial',
    fontSize: 20,
    fontWeight: '800',
    color: '#1A2D27',
  },
  subtitle: {
    fontFamily: 'Arial',
    fontSize: 16,
    textAlign: 'center',
    color: '#8A9994',
    lineHeight: 20,
  },
  actions: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
  },
  cancelButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: '#F0F3F2',
  },
  cancelButtonText: {
    color: '#4A5C57',
    fontWeight: '700',
  },
  confirmButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: '#2F5D50',
  },
  confirmButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
});